update-check: true

addons:
  PlaceholderAPI: true
  CMILib: false
  FastLogin: false

config:
  titles:
    register:
      time: #This is a times of title in ticks.
        fadein: 5
        stay: 30
        fadeout: 5
    login:
      time: #This is a times of title in ticks.
        fadein: 5
        stay: 30
        fadeout: 5
    autologin:
      time: #This is a times of title in ticks.
        fadein: 5
        stay: 30
        fadeout: 5
  actionbar:
    enabled: true
    register:
      time: #This is time of stay message in seconds.
        stay: 5
    login:
      time: #This is time of stay message in seconds.
        stay: 5
    autologin:
      time: #This is time of stay message in seconds.
        stay: 5
  bossbar:
    enabled: true
    color: RED #ONLY WORK IN 1.9 TO UP
    style: SOLID #ONLY WORK IN 1.9 TO UP
    register:
      time: #This is time of stay message in seconds.
        stay: 5
    login:
      time: #This is time of stay message in seconds.
        stay: 5
    autologin:
      time: #This is time of stay message in seconds.
        stay: 5
  message:
    welcome:
      onjoin:
        register:
          enabled: false
          center: true
        login:
          enabled: false
          center: true
      register: #This message is customizable in lang.yml - "center" is so that the message is centered in the chat
        enabled: true
        center: true
      login: #This message is customizable in lang.yml - "center" is so that the message is centered in the chat
        enabled: true
        center: true
      autologin: #This message is customizable in lang.yml - "center" is so that the message is centered in the chat
        enabled: true
        center: true