name: UTitleAuth
version: ${project.version}
author: [UnDeadlyDev]
main: com.undeadlydev.UTitleAuth.TitleAuth
depend: [AuthMe]
api-version: 1.13
softdepend: 
  - PlaceholderAPI
  - CMILib
  - FastLogin
